# Generated by Django 4.2.4 on 2023-08-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='iwr',
            field=models.DecimalField(decimal_places=9, max_digits=19),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rmsse',
            field=models.DecimalField(decimal_places=9, max_digits=19),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='total_co',
            field=models.DecimalField(decimal_places=9, max_digits=19),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='total_co2',
            field=models.DecimalField(decimal_places=9, max_digits=19),
        ),
    ]
