# Generated by Django 4.2.4 on 2023-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdt_app', '0002_alter_testresults_iwr_alter_testresults_rmsse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(choices=[('Vehicle A', 'Vehicle A'), ('Vehicle B', 'Vehicle B'), ('Vehicle C', 'Vehicle C'), ('Vehicle D', 'Vehicle D'), ('Vehicle E', 'Vehicle E'), ('Vehicle F', 'Vehicle F'), ('Vehicle G', 'Vehicle G')], max_length=20),
        ),
    ]
