# Generated by Django 4.2.4 on 2023-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdt_app', '0003_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='vehicle_id',
            field=models.CharField(choices=[('Vehicle A', 'Vehicle A'), ('Vehicle B', 'Vehicle B'), ('Vehicle C', 'Vehicle C'), ('Vehicle D', 'Vehicle D'), ('Vehicle E', 'Vehicle E'), ('Vehicle F', 'Vehicle F'), ('Vehicle G', 'Vehicle G')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
