# Generated by Django 4.2.4 on 2023-08-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdt_app', '0006_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdt_app.cell'),
        ),
    ]
